const warehouseReceiptLocators = {
    createNewButton: '.CreateNew',
    wrHeading: "//app-receipt-form//div[@class='text-container']//h2",
    warehouseReceiptField: '#WarehouseId-field',
    DropdownList: "//cyz-infinite-scroll//mat-option//span[@class='mat-option-text']",
    statusField: '#StatusId-field',
    shipperNameField: '#Shipper_id',
    formDropdownList: "//span//p[@class='mat-tooltip-trigger']",
    shipperLocation: '//div//mat-select[@id="Shipper_location"]',
    locationDropdownList: "//cyz-infinite-scroll//mat-option",
    upArrowBlue: "//button//img[contains(@src, 'up-arrow-blue.svg')]",
    consigneeNameField: '#Consignee_id',
    consigneeLocation: '#Consignee_location',
    shipperpointOfContact: "(//mat-select[@id='point-of-contact' and @aria-disabled='false'])[1]",
    consigneepointOfContact: "(//mat-select[@id='point-of-contact' and @aria-disabled='false'])[2]",
    agentpointOfContact: "(//mat-select[@id='point-of-contact' and @aria-disabled='false'])[3]",
    consigneeContactCheckboxDropdown: "//cyz-infinite-scroll//mat-option[@class='mat-option mat-focus-indicator mat-tooltip-trigger mat-option-multiple ng-star-inserted']",
    agentNameField: '#Agent_id',
    agentLocation: '#Agent_location',
    supplierNameField: '#Supplier_id',
    supplierLocation: '#Supplier_location',
    submitButton: "//div//button[@id='submit-button']",
    loader: "//div[@class='loader-new true']",
    successMessage: "//div[@class='message-holder']",
    packageTab: "(//div[@class='mat-tab-links']//a)[2]",
    loadingImage: "//div[@class='k-loading-image ng-star-inserted']",
    inlineButton: "//div//option-menu-list//button[@class='mat-focus-indicator mat-menu-trigger mat-button mat-button-base ng-star-inserted']",
    inlineOptions: "//div//button[@class='mat-focus-indicator mat-menu-item ng-star-inserted']",
    createNewDropdownButton: "(//button//span[contains(@class, 'mat-button-wrapper') and contains(text(), 'Create New')])[1]",
    createNewDropdownOption: "//div[contains(@class,'mat-menu-content')]//button[@role='menuitem']",
    createMultiple: "//div[contains(@class,'mat-menu-content')]//button[contains(text(),' Create Multiple')] ",
    packageFormDialogBox: "//form//div[@class='heading']",
    packageTypeField: "#PackageTypeId-field-multi",
    packageTypeDropdownList: "//cyz-infinite-scroll//mat-option[@class='mat-option mat-focus-indicator mat-tooltip-trigger ng-star-inserted']",
    dimensionsField: '#dimensions',
    lengthField: "//input[@name='Length']",
    widthField: "//input[@name='Width']",
    heightField: "//input[@name='Height']",
    weightField: "//div//input[@formcontrolname='Weight']",
    noOfPiecesField: "//div//input[@formcontrolname='NumberOfPieces']",
    createButton: '#multi-submit-button',
    locationField: "(//autocomplete-field[@matlabel='Location'])[1]",
    searchButton: "(//autocomplete-field[@matlabel='Location'])[1]//button",
    kendoGrid: "//div//kendo-grid[@class='list-view-new allow-open-new-tab show-if-truncated k-grid loaded']",
    row: "//kendo-grid[contains(@class,'list-view-new')]//tbody//tr[contains(@class,'k-master-row')]",
    rowRadioButton: "//kendo-grid[contains(@class,'list-view-new')]//tbody//tr[contains(@class,'k-master-row')]//label[contains(@class,'mat-radio-label')]",
    warehouseField: "//div//dropdown-field[@matlabel='Warehouse']",
    warehouseDropdownList: "//cyz-infinite-scroll//mat-option//span[@class='mat-option-text']",
    userImage: "//app-header//li[@class='userImage']",
    loader: "//div[@class='loader-new true']",
    logoutButton: "//app-header//a[contains(@class,'dropdown-item') and contains(text(),'Logout')]"



}


module.exports = warehouseReceiptLocators;